<a href="https://colab.research.google.com/github/cristiangomez811/aprendizaje_python/blob/master/python_deep_learning/Cap3_Python_y_Librerias.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cap 2 Entorno de trabajo 

En esta sección voy a colocar la parte de configuración  
del entorno de trabajo del captitulo 2.

In [61]:
#Comando para especificar la versión de TensorFlow
%tensorflow_version 2.x

In [62]:
#Importar la libreria TF
import tensorflow as tf

#Validar si hay disponible una GPU
print("GPU Available: ", tf.config.list_physical_devices('GPU'))

GPU Available:  [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [63]:
# Versión de TF 
print(tf.__version__)

2.3.0


In [64]:
#Para Keras
from tensorflow import keras
print(tf.keras.__version__)

2.4.0


# Cap 3 Python y sus librerías

Capitulo enfocado en el lenguaje python. 



In [65]:
#Comando help para python
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(...)
 |      S.__format__(format_spec) -> str
 |      
 |      Return a formatted version of S as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getatt

In [66]:
#Comando útil para ver los metodos de un objeto 
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [67]:
#Importación de librerías mediante las palabras reservadas 'from' e 'import'
from random import randint
randomint = randint(1,100)
print(randomint)

9


In [68]:
import random
randomint = random.randint(1,100)
print(randomint)

17


### Tipos de datos y estructuras en python

In [69]:
# basicos

x = 10 
print(x)
print(type(x))

x = "hola"
print(x)
print(type(x))

x = 10.0
print(x)
print(type(x))

x = True
print(x)
print(type(x))

10
<class 'int'>
hola
<class 'str'>
10.0
<class 'float'>
True
<class 'bool'>


In [70]:
#Operadores basicos
print(5/2)
print(5//2) #División redondeada
print(5%2)
print(5**2)


2.5
2
1
25


In [71]:
# operadores += y -= 
IntegerVar = 10 
IntegerVar += 10 
print (IntegerVar)

StringVar = "Deep"
StringVar += " Learning"
print (StringVar)

20
Deep Learning


In [72]:
# asigunasiones multiples
IntegerVar, StringVar = StringVar, IntegerVar
print(IntegerVar)
print(StringVar)

Deep Learning
20


#### Estructuras de datos

In [73]:
# listas
x = [5,"hello",1.8]
print(x)
len(x)

[5, 'hello', 1.8]


3

In [74]:
x.append(100)
print(x)
print(len(x))

[5, 'hello', 1.8, 100]
4


In [75]:
x[1] = "Deep"
print(x)

[5, 'Deep', 1.8, 100]


In [76]:
# concatenar listas
y = [2.1,"learning"]
z = x + y
print (z)

[5, 'Deep', 1.8, 100, 2.1, 'learning']


In [77]:
#indexación de listas
x = [5,"deep",1.8]
print("primer elemento --> x[0]: ", x[0])
print("segundo elemento --> x[1]: ", x[1])
print("último elemento --> x[-1]: ", x[-1])
print("penúltimo elemento --> x[-2]: ", x[-2])

primer elemento --> x[0]:  5
segundo elemento --> x[1]:  deep
último elemento --> x[-1]:  1.8
penúltimo elemento --> x[-2]:  deep


In [78]:
print("todos los índices --> x[:]: ", x[:])
print("desde el índice 1 hasta el final --> x[1:]: ", x[1:])
print("desde el índice 1 hasta el 2 (no se incluye el 2) [1,2) ) --> x[1:2]: ", x[1:2])
print("desde el índice 0 hasta el final sin incluir al último --> x[:-1]: ", x[:-1])

todos los índices --> x[:]:  [5, 'deep', 1.8]
desde el índice 1 hasta el final --> x[1:]:  ['deep', 1.8]
desde el índice 1 hasta el 2 (no se incluye el 2) [1,2) ) --> x[1:2]:  ['deep']
desde el índice 0 hasta el final sin incluir al último --> x[:-1]:  [5, 'deep']


In [79]:
#tuplas, son colecciones ¡inmutables! 
x = (1,"deep",3)
print(x)
print(x[1])


(1, 'deep', 3)
deep


In [80]:
x = x + (4,"learning")
print(x)
print(x[-1])

(1, 'deep', 3, 4, 'learning')
learning


In [81]:
# Dicionarios
persona = {'nombre': 'Cristian Gomez',
           'profesion': 'Data Science'}
print (persona)
print (persona['nombre'])
print (persona['profesion'])

{'nombre': 'Cristian Gomez', 'profesion': 'Data Science'}
Cristian Gomez
Data Science


In [82]:
persona['profesion'] = 'Ingeniero'
print (persona)

{'nombre': 'Cristian Gomez', 'profesion': 'Ingeniero'}


In [83]:
persona['grupo'] = 24
print (persona)

{'nombre': 'Cristian Gomez', 'profesion': 'Ingeniero', 'grupo': 24}


In [84]:
print (len(persona))

3


### Sentencias de control y funciones

In [85]:
# setencia if
x = 6.5 
if x < 5: 
    puntuacion = 'baja'
elif x <= 7: # elif = else if
    puntuacion = 'media'
else: 
    puntuacion = 'alta'

print(puntuacion)

media


In [86]:
b = 1
print ("Paris" if b >= 92 else "Barcelona")

Barcelona


In [87]:
# bucle for
for a in range (1,4): 
    print (a)

1
2
3


In [88]:
universidades = ["UPB","UdA","UNAL"]
for universidad in universidades:
    print (universidad)

UPB
UdA
UNAL


In [89]:
for universidad in universidades:
    if universidad == "UdA":
        break #termina el bucle, no procesa más elementos de la lista
    print (universidad)

UPB


In [90]:
for universidad in universidades:
    if universidad == "UdA":
        continue #omite el item acual, pero continua el bucle
    print (universidad)

UPB
UNAL


In [91]:
# Bucle while

x=3 
while x > 0: 
    x = x - 1
    print(x)

2
1
0


### Funciones

In [93]:
# declaración de funciones
def mi_universidad (universidad = 'UPB'):
    y = "Mi universidad es la " + universidad
    return (y)

print (mi_universidad("UDM"))
print (mi_universidad(universidad = "UNAL"))
print (mi_universidad())

Mi universidad es la UDM
Mi universidad es la UNAL
Mi universidad es la UPB


In [94]:
# funciones con argumentos iniciales
def foo():
    a, b = 4, 5
    return a, b

foo()

(4, 5)

In [96]:
# Funciones lambda, funciones anonimas

fibonacci = (lambda x:1 if x <= 2 else 
             fibonacci(x-1) + fibonacci(x-2))

fibonacci(10)


55

### Clases en python 

In [100]:
# Definición e iniciación de clases
class Calculadora(object):
    """Clase de una calculadora"""

    def __init__(self):
        """Inicializa la clase calculadora"""
        self.valor = 0

    def suma(self,n):
        """suma un numero n al valor"""
        self.valor += n

    def getValor(self):
        """obtiene el valor"""
        return self.valor

In [101]:
calc = Calculadora() # iniciar la clase
calc.suma(2)
print (calc.getValor())
calc.suma(2)
print (calc.getValor())

2
4


In [102]:
vec = [1, 2, 3]
it = iter(vec) # iterador

next(it)

1

In [103]:
next(it)

2

In [104]:
type(vec) # iterable

list

In [105]:
type(it) # iterador

list_iterator

### Decoradores

Ejecucciones que se hacen pre o post procesamiento de una función

In [106]:
# sin decorador
def voy_a_imprimir_Hola():
    print("Hola")

voy_a_imprimir_Hola()

Hola


In [107]:
# con decorador
def voy_a_imprimir_Hola():
    print("Hola")

def my_decorator(func):
    def wrapper ():
        print("[Aviso: voy a decir algo]")
        func ()
        print("[Aviso: ya he dicho algo]")
    return wrapper

voy_a_imprimir_Hola = my_decorator(voy_a_imprimir_Hola)

voy_a_imprimir_Hola ()

[Aviso: voy a decir algo]
Hola
[Aviso: ya he dicho algo]


In [108]:
# se puede hacer uso de los decoradores mediante la siguiente estructura
@my_decorator 
def voy_a_imprimir_Hola():
    print("Hola")

In [110]:
voy_a_imprimir_Hola()

[Aviso: voy a decir algo]
Hola
[Aviso: ya he dicho algo]


## Tensores

es un array multidimencional de *Numpy*, los tensores se usan como estructura básica de datos.

Un **tensor** tiene tres atributos principales: número de ejes, forma y tipo de datos. 

* **Numero de ejes (rank):** es un numero que muestra la cantidad de dimensiones en él. Un escalar (0D) es un tensor con un solo número. Un array de números es un vector o tensor de 1D. Un array de vectores es una matriz o tensor de 2D. Con esta estructura se pueden tener tensores de nD (n número de dimsniones). En NumPy a esto se le llama *ndim* del tensor

* **Forma:** es una tupla con la cantidad de items en cada eje. En NumPy a esto se le llama *shape*. Un escalar tiene shape vacío ()

* **Tipo de datos:** Indica el tipo de dato que contiene el tensor. En NumPy a esto se le llama *dtype*



In [119]:
# Tensor en NumPy

import numpy as np

def mostrar_tensor(x):
    print("x: \n ",x)
    print("x ndim: ",x.ndim)
    print("x shape: ", x.shape)
    print("x size: ",x.size)
    print("x dtype: ",x.dtype)

In [120]:
# para un escalar
x = np.array(8)

mostrar_tensor(x)

x: 
  8
x ndim:  0
x shape:  ()
x size:  1
x dtype:  int64


In [121]:
# para un vector

x = np.array([2.3,4.2,3.3,1.8])

mostrar_tensor(x)

x: 
  [2.3 4.2 3.3 1.8]
x ndim:  1
x shape:  (4,)
x size:  4
x dtype:  float64


In [122]:
# para una matriz 2D
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

mostrar_tensor(x)

x: 
  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim:  3
x shape:  (2, 2, 2)
x size:  8
x dtype:  int64


In [123]:
# Funciones de Numpy para crear tensores rapidamente

print("np.zeros((3,3)): \n", np.zeros((3,3)))
print("np.ones((3,3)): \n", np.ones((3,3)))
print("np.eye((3)): \n", np.eye((3)))
print("np.random.random((3,3)): \n", np.random.random((3,3)))

np.zeros((3,3)): 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
np.ones((3,3)): 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
np.eye((3)): 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
np.random.random((3,3)): 
 [[0.3604038  0.95126353 0.94329763]
 [0.71598144 0.52319944 0.09161609]
 [0.94669471 0.70072308 0.66250434]]


### Manipulación de tensores